name: main
on: [push, pull_request]

jobs:
  testing-conda:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          mamba-version: "*"
          environment-file: conda/local.yaml
          channels: conda-forge,nodefaults
          activate-environment: shinyapp
          use-mamba: true
          miniforge-variant: Mambaforge

      - name: install from poetry
        run: poetry install

      - name: run shiny app
        run: |
          shiny run app.py &
          sleep 5 &
          kill %%
